# Generated by Django 3.2.16 on 2024-11-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20241120_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='Если установить дату и время в будущем— можно делать отложенные публикации.', verbose_name='Дата и время публикации'),
        ),
    ]
